tminnovation/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import url, include


urlpatterns = [
    path('tramino/', include('tramino.urls')),
    path('admin/', admin.site.urls),
]


"""
ローカルで画像を表示するpathを追加
"""
from django.conf import settings
from django.conf.urls.static import static
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # 追加

tramino/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views
# from tminnovation import settings

app_name = 'tramino'
urlpatterns = [
    # path('hp/', views.hp, name = 'hp'),
    path('index/', views.index, name = 'index'),
    path('mypage/', views.mypage, name='mypage'),
    path('schedule/', views.schedule, name='schedule'),
    path('match_search/', views.match_search, name='match_search'),
    path('match_refine/', views.match_refine, name='match_refine'),
    path('match_detail/<int:event_id>/', views.match_detail, name='match_detail'),
    path('match_detail/update/<int:pk>/', views.EventUpdateView.as_view(), name='edit_event'),
    path('match_detail/delete/<int:pk>/', views.EventDeleteView.as_view(), name='delete_event'),
    path('event_post/', views.event_post, name='event_post'),
    path('team_search/', views.team_search, name='team_search'),
    path('team_detail/<int:team_id>/', views.team_detail, name='team_detail'),
    path('create/', views.create, name='create'),
    path('save_school_info/', views.save_school_info, name='save_school_info'),
    path('school_list/', views.school_list, name='school_list'),
    path('school_info/', views.school_info, name='school_info'),
    path('done/', views.done, name='done'),
    # path('logout/', views.logout, name='logout'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('user_create/', views.UserCreate.as_view(), name='user_create'),
    path('user_create/done', views.UserCreateDone.as_view(), name='user_create_done'),
    path('user_create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    path('myteams/',views.MyTeamsListView.as_view(), name='myteams'),
    path('myteams/detail/<int:pk>/', views.MyTeamsDetailView.as_view(), name='myteams_detail'),
    path('myteams/update/<int:pk>/', views.MyTeamsUpdateView.as_view(), name='edit_myteams'),
    path('myteams/delete/<int:pk>/', views.MyTeamsDeleteView.as_view(), name='delete_myteams'),
    path('user_update/',views.UserUpdateView.as_view(), name='user_update'),
    path('past_game_post/', views.past_game_post, name='past_game_post'),
    path('myteams/delete_past_game/<int:pk>/', views.PastGameDeleteView.as_view(), name='delete_past_game'),
    path('message_home/', views.message_home, name='message_home'),
    path('message_home/<str:room_name>/', views.message_room, name='message_room'),
    path('message_template', views.message_template, name='message_template'),
]

tramino/views.py
#from django.shortcuts import render
from django.http.response import JsonResponse
from django.http.response import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth.models import User

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (
    LoginView, LogoutView
)



""" import models or forms """
from .models import TeamInformations, EventPostPool, EventApplyPool, FavoriteEventPool,FavoriteTeamPool,PastGameRecords
from .forms import EventPostPoolForm, EventPostUpdateForm, MessageForm, PastGameRecordsForm, UserCreateForm, TeamInfoForm
from .forms import LoginForm

""" python code in python_file """
from .python_file.model_form_save import *
from .python_file import message
from .python_file.profile_complete_percent import *
from .python_file.schedule_process import *
from .python_file.model_to_dict import *
from .python_file.email_process import *
from .python_file.views_params_generator import *
from .python_file.school_list import *


""" 08/10以降追加 """
from django.shortcuts import get_object_or_404, resolve_url

from django.views import generic
from django.views.generic import ListView, UpdateView, DetailView, UpdateView, DeleteView, CreateView
import datetime
from email.mime.text import MIMEText
import smtplib
from django.contrib.auth import get_user_model
from django.contrib.sites.shortcuts import get_current_site
from django.core.signing import BadSignature, SignatureExpired, loads, dumps
from django.core import serializers
from django.http import Http404, HttpResponseBadRequest
from django.conf import settings
from django.template.loader import render_to_string
# Create your views here.

import json
import os

User = get_user_model()


class UserCreate(generic.CreateView):
    """ユーザー仮登録"""
    template_name = 'tramino/register/user_create.html'
    form_class = UserCreateForm

    def form_valid(self, form):
        """仮登録と本登録用メールの発行."""
        # 仮登録と本登録の切り替えは、is_active属性を使うと簡単です。
        # 退会処理も、is_activeをFalseにするだけにしておくと捗ります。
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # アクティベーションURLの送付
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': self.request.scheme,
            'domain': domain,
            'token': dumps(user.pk),
            'user': user,
        }

        subject = render_to_string('tramino/register/mail_template/create/subject.txt', context)
        message = render_to_string('tramino/register/mail_template/create/message.txt', context)

        user.email_user(subject, message)
        return redirect('tramino:user_create_done')


class UserCreateDone(generic.TemplateView):
    """ユーザー仮登録状態"""
    template_name = 'tramino/register/user_create_done.html'


class UserCreateComplete(generic.TemplateView):
    """メール内URLアクセス後のユーザー本登録"""
    template_name = 'tramino/register/user_create_complete.html'
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)  # デフォルトでは1日以内

    def get(self, request, **kwargs):
        """tokenが正しければ本登録."""
        token = kwargs.get('token')
        try:
            user_pk = loads(token, max_age=self.timeout_seconds)

        # 期限切れ
        except SignatureExpired:
            return HttpResponseBadRequest()

        # tokenが間違っている
        except BadSignature:
            return HttpResponseBadRequest()

        # tokenは問題なし
        else:
            try:
                user = User.objects.get(pk=user_pk)
            except User.DoesNotExist:
                return HttpResponseBadRequest()
            else:
                if not user.is_active:
                    # 問題なければ本登録とする
                    user.is_active = True
                    user.save()
                    return super().get(request, **kwargs)

        return HttpResponseBadRequest()


class Login(LoginView):
    """ログインページ"""
    form_class = LoginForm
    template_name = 'tramino/login.html'


class Logout(LoginRequiredMixin, LogoutView):
    """ログアウトページ"""
    template_name = 'tramino/index.html'


def index(request):
    try:
        params = {
            'id':request.user.id,
            'email':request.user.email,
        }
        return render(request, 'tramino/index.html', params)
    except:
        params = {
            'id': "なし",
            'email': "なし"
        }
        return render(request, 'tramino/index.html', params)


def mypage(request):
    if request.method == 'POST':
        form = TeamInfoForm(request.POST, request.FILES)
        if form.is_valid():
            TeamInfoSave(request)
    params = generate_mypage_params(request)
    return render(request, 'tramino/mypage.html', params)


def schedule(request):
    my_teams = TeamInformations.objects.filter(user=request.user.id)
    my_teams_id = []
    for my_team in my_teams:
        my_teams_id.append(my_team.id)
    schedule_data_set,calendar_data_set = schedule_dataset_generator(my_teams_id,EventPostPool.objects.all(),EventApplyPool.objects.all())
    params = {
        'schedule_data_set': schedule_data_set,
        'calendar_data_set': calendar_data_set,
        }
    return render(request, 'tramino/schedule.html', params)


def match_search(request):

    # else:
    # event_post_pool = EventPostPool.objects.all()
    #
    # username = request.user.username
    # my_teams = TeamInformations.objects.filter(user=request.user.id)
    # my_teams_id = []# 自分のチームIDを持つイベントを表示しないようにする
    # for my_team in my_teams:
    #     my_teams_id.append(my_team.id)
    # for i,my_team_id in enumerate(my_teams_id):
    #     event_post_pool = event_post_pool.exclude(event_host_team=my_team_id)
    # event_post_pool = day_of_the_week(event_post_pool)
    # params = {
    #     'events': event_post_pool,
    #     'username': username,
    # }
    params = {}
    return render(request, 'tramino/match_search.html', params)


def match_refine(request):
    """
    　募集を絞る時のajax関数
    """
    if request.method == "POST":
        host_team = request.POST['event_host_team']
        prefectures = request.POST['prefecture']
        club_name = request.POST['club_name']
        number_of_members = request.POST['number_of_members']
        achievement = request.POST['achievement']
        date1 = request.POST['date1']
        date2 = request.POST['date2']


        event_post_pool = EventPostPool.objects.none()
        teams = TeamInformations.objects.filter(organization_name__contains=host_team)
        teams = teams.filter(prefectures_name__contains=prefectures)
        teams = teams.filter(club_name__contains=club_name)

        teams = teams.filter(achievement__contains=achievement)

        for team in teams:
            event_post_pool = event_post_pool | team.event_posts.all()

        event_post_pool = event_post_pool.filter(event_date__range=[date1, date2])

    event_post_pool = day_of_the_week(event_post_pool)
    event_post_pool = make_model_list(event_post_pool)
    ret = {"data": event_post_pool}
    return JsonResponse(ret)


def match_detail(request, event_id):
    """
    GET : match_searchやteam_detail,mypageのリンクから移動してくる
    POST : match_detailからイベントをファボした際POSTで入りなおす
    """
    message = ""
    username = request.user.username
    match  = EventPostPool.objects.get(id=event_id)
    my_teams = TeamInformations.objects.filter(user=request.user.id)
    my_teams_name = []
    for my_team in my_teams:
        my_teams_name.append(my_team.organization_name)
    match.host_team_id = match.event_host_team.id# イベント詳細ページからチーム詳細に飛ぶためのURL生成に必要なイベントホストチームID
    match = match_and_deadline_day_of_the_week(match)
    applies = EventApplyPool.objects.all().filter(event_post_id=event_id)
    if request.method == 'POST':
        if request.POST['page_name'] == 'event_favorite':

            event_id, apply_team_id = request.POST['event_id'], request.POST['apply_team_id']
            apply = FavoriteEventPool()
            apply.event_post_id, apply.guest_team_id = EventPostPool.objects.get(id=event_id) ,TeamInformations.objects.get(id=apply_team_id)
            favorited_events = FavoriteEventPool.objects.all().filter(guest_team_id=apply.guest_team_id.id)
            if apply.event_post_id.id in list(favorited_events.values_list('event_post_id',flat=True)):
                FavoriteEventPool.objects.all().filter(guest_team_id=apply.guest_team_id.id).get(event_post_id=apply.event_post_id.id).delete()
                message = '気になるを取り消しました。'
            elif int(match.host_team_id) == int(apply.guest_team_id.id):
                message = '同チームのイベントは気になるリストに追加できません'

            else:
                apply.save()
                message = '気になるに追加しました。'

    my_teams_id = []
    for my_team in my_teams:
        my_teams_id.append(my_team.id)

    if match.host_team_id in my_teams_id:# 自分のチームの投稿なら応募やファボをできないようにする
        params = {
            'match': match,
            'username': username,
            'applies' : applies,
            'message' : message,
        }
    else:# 気になる済みかどうかの判定
        for i,my_team_id in enumerate(my_teams_id):
            favo = list(FavoriteEventPool.objects.all().filter(guest_team_id=my_team_id).values_list('event_post_id',flat=True))
            if int(event_id) in favo:
                my_teams[i].favo_judge = 'の気になるリストから取り消す'
            else:
                my_teams[i].favo_judge = 'の気になるリストに追加する'
        form = MessageForm()
        params = {
            'form': form,
            'match': match,
            'my_teams': my_teams,
            'my_teams_name':my_teams_name,
            'username': username,
            'applies' : applies,
            'message' : message,
        }
    return render(request, 'tramino/match_detail.html', params)


def event_post(request):
    username = request.user.username
    my_teams = TeamInformations.objects.filter(user=request.user.id)
    my_teams_name = []

templates/tramino/base.html
<!-- {% load static%} -->
<!DOCTYPE html>
<html lang="ja">
<head>
    <title>tramino</title>

    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.auto.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
    
    <script type="text/javascript" src="https://code.jquery.com/jquery-latest.min.js"></script>

    <style type="text/css">
    body{
        margin: 0;
        padding: 0;
    }
    header{
        width: 100%;
        height: 80px;
        background-color: rgb(71, 71, 71);
    }
    /*ロゴ画像*/
    .logo{
        float: left;
        width: 14%; /*imgの幅*/
        line-height: 80px; /*heightの高さと同じに*/
        margin: 0;
    }
    .logo-image{
        line-height: 60px; /*heightの高さと同じに*/
        vertical-align: middle;
        width: 80%;
        margin-left: 50px;
        /*position: absolute;
        top: 50%;
        transform: translateY(-50%);*/
    }
    .message-image{
        line-height: 25px; /*heightの高さと同じに*/
        vertical-align: middle;
        width: 25%;
        margin-left: 30px;
        /*position: absolute;
        top: 50%;
        transform: translateY(-50%);*/
    }
    /*メニュー*/
    .header-menu{
        float: right;
        line-height: 80px; /*headerの高さと同じに*/
    }
    .header-menu ul{
        margin: 0;
        padding: 0;
    }
    .header-menu li{
        display: inline-block;
        margin-right: 10px;
    }
    .header-menu li a{
        text-decoration: none;
        color: rgb(226, 226, 226);
        font-family:'MingLiU';
        font-size:20px;
    }
    </style>

    {% block css %}{% endblock %}
</head>


<body>
  <!-- <p><a href="{% url 'tramino:create' %}">create</a></p> -->
  <!-- <a href="{% url 'tramino:mypage' %}">マイページ</a>
  <p>logged in as {{ username }}</p>
  <hr> -->

  <!-- header -->
  <header>
    <!-- logo画像 -->
    <h1 class="logo">
        <a href="{% url 'tramino:mypage' %}"><img src="{% static 'tramino\base\images\tramino_logo.png'%}" class="logo-image"></a>
    </h1>

    <!-- メニュー -->
    <div class="header-menu">
        <ul>
            <li><a href="{% url 'tramino:login' %}">in</a></li>
            <li><a href="{% url 'tramino:logout' %}">out</a></li>
            <li><a href="{% url 'tramino:index' %}">確認</a></li>
            <li><a href="{% url 'tramino:match_search' %}">ゲームを検索</a></li>
            <li><a href="{% url 'tramino:team_search' %}">チームを検索</a></li>
            <li><a href="{% url 'tramino:event_post' %}">対戦相手を募集</a></li>
            <!-- <li><a href="">menu4</a></li> -->
            <li><a href="{% url 'tramino:message_home' %}"><img src="{% static 'tramino\base\images\message_icon.svg'%}" class="message-image"></a></li>
        </ul>
    </div>
  </header>


  {% block content %}{% endblock %}
</body>
</html>

{% block js %}{% endblock %}

templates/tramino/match_detail.html
{% extends 'tramino/base.html' %}
{% load static %}

{% block css %}
<style type="text/css">
  .card2 {
      width: 900px;
      margin: 20px;
      border-radius: 5px;
      background-color: #fff;
      box-shadow: 0 3px 6px #ccc;
  }
  .box2 {
      display: flex;
  }
  .icon2 {
      width: 85px;
      height: 85px;
      margin: 10px;
      border-radius: 24px;
      object-fit: cover;
  }
  .name2 {
      font-size: 100%;
      margin-bottom: 10px;
      color: #888;
  }
  .image2 {
      width: 100%;
      height: 550px;
      object-fit: cover;
  }
  .title2 {
      font-size: 150%;
      margin: 10px 0;
      color: #444;
  }
  .content2 {
      padding: 10px;
      color: #666;
  }
</style>
<style type="text/css">
  .card5 {
      width: 700px;
      margin: 20px;
      border-radius: 5px;
      background-color: #fff;
      box-shadow: 0 3px 6px #ccc;
  }
  .box5 {
      display: flex;
  }
  .icon5 {
      width: 60px;
      height: 60px;
      margin: 10px;
      border-radius: 24px;
      object-fit: cover;
  }
  .name5 {
      font-size: 100%;
      margin-bottom: 10px;
      color: #888;
  }
  .image5 {
      width: 40%;
      height: 150px;
      object-fit: cover;
  }
  .title5 {
      font-size: 150%;
      margin: 10px 0;
      color: #444;
  }
  .content5 {
      padding: 10px;
      color: #666;
  }
</style>

{% endblock %}


{% block content %}
  <h3>メッセージアラート：{{ message }}{{ event_apply_status }}</h3>
  <h1>試合の詳細</h1>
<div class="card2">
  <div class="box2">
      <img src="{{match.event_host_team.commander_picture.url}}" class="icon2">
      <div>
        <div class="title2" style="width:700px;text-align:left;">
        <div style="text-align:right;float:right;">{{match.event_date}}({{match.dot_week}})</div>{{match.event_name}}</div>
          <p class="name2"><a href="{% url 'tramino:team_detail' match.host_team_id %}" style="text-decoration: none;">{{ match.event_host_team.organization_name }}{{ match.event_host_team.club_name }}({{ match.event_host_team.school_attribute }})</a></p>
      </div>
  </div>
  {% if match.event_host_team.activity_place_picture != "SOME STRING" %}
  <img src="{{ match.event_host_team.activity_place_picture.url }}" class="image2">
  {% elif match.event_host_team.team_picture != "SOME STRING" %}
  <img src="{{ match.event_host_team.team_picture.url }}" class="image2">
  {% else %}
  <img src="{% static 'tramino\mypage\images\question_mark.png'%}" class="image2">
  {% endif %}
  <p class="content2">{{match.event_description}}</p>
  <div class="title2" style="width:800px;text-align:left;">
  <div style="text-align:right;float:right;">あと〇〇日！！</div>申し込み期限 : {{match.apply_deadline}}({{ match.deadline_dotw }})</div>

</div>
  <!-- <h2><a href="{% url 'tramino:team_detail' match.host_team_id %}">チームの詳細を見る</a></h2> -->
<br>

  <form action="{% url 'tramino:message_template' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="matchid" value={{ match.id }}>
    <input type="submit" value="メッセージを作成">
  </form>
<br>

  <h2>応募済みのチーム</h2>
  <table class="table">
    <tbody>
      {% for apply in applies %}
      <tr>
        <th><a href="{% url 'tramino:team_detail' apply.guest_team_id.id %}">{{ apply.guest_team_id.organization_name }}{{ apply.guest_team_id.club_name }}({{ apply.guest_team_id.school_attribute }})</a></th>
      </tr>
      {% endfor %}
    </tbody>
  </table>


--------------------↓↓↓↓気になるリストに追加↓↓↓↓---------------------
  <br>
  <h2>気になるリストに追加</h2>

  {% for myteam in my_teams %}
  <form action="{% url 'tramino:match_detail' match.id %}" method="POST" enctype="multipart/form-data">
  <!-- <form method="post" action="{% url 'tramino:done' %}"> -->
  {% csrf_token %}
  <tbody>
    <tr>
      <th><input class="btn btn-primary" type="submit" value="{{ myteam.organization_name }}{{ myteam.club_name }}({{ myteam.school_attribute }}){{ myteam.favo_judge }}"></th>
      <td><input class="btn btn-secondary" type="reset" value="Reset"></td>
    </tr>
  </tbody>
  <input type="hidden" name="page_name" value="event_favorite">
  <input type="hidden" name="event_id" value={{match.id}}>
  <input type="hidden" name="apply_team_id" value={{myteam.id}}>
  </form>
  {% endfor %}




  <p><a href="{% url 'tramino:match_search' %}">試合を探す</a></p>

  {% endblock %}

  {% block js %}
  <script>
    function clickBtn1(){

      const teamnamechoice = document.form1.teamnamechoice;

      // 値(数値)を取得
      const num = teamnamechoice.selectedIndex;
      //const num = document.form1.color1.selectedIndex;

      // 値(数値)から値(value値)を取得
      const str = teamnamechoice.options[num].value;
      //const str = document.form1.color1.options[num].value;

      document.getElementById("team_name").value = str;
      console.log("done");
    }
    </script>


  {% endblock %}

templates/tramino/mypage.html
{% extends 'tramino/base.html' %}
{% load static %}
{% block css %}
<link rel='stylesheet' type='text/css' href="{% static 'tramino\mypage\css\mypage_1.css'%}" />
<link rel='stylesheet' type='text/css' href="{% static 'tramino\mypage\css\mypage_2.css'%}" />
<link href='https://fonts.googleapis.com/css?family=Oswald:300' rel='stylesheet' type='text/css'>

<style>
</style>

{% endblock%}

{% block content %}
<div class="mypage-main-box">
  <div class="mypage-main-info">
    <h1 class="mypage-title">My Page Contents</h1>

    <a href="{% url 'tramino:myteams' %}" class="mypage-btn">登録チームの追加・確認</a>
    <a href="{% url 'tramino:schedule' %}" class="mypage-btn">スケジュール</a>
    <!-- <a href="#" class="mypage-btn">メッセージテンプレートの作成</a> -->
    <a href="{% url 'tramino:user_update' %}" class="mypage-btn">ユーザー情報変更</a>
    <br><br><br><br>
    <div>
      {% if commander_pic == 0 %}
        <img src="{% static 'tramino\mypage\images\question_mark.png'%}" class="commander-img"></a>
      {% else %}
        <img src="{{ commander_pic.url }}" class="commander-img"/>
      {% endif %}
    </div>    
      {% if commander_info == 0 %}
        <a href="" target="_blank" class="mypage-info-footer">ログインまたはチームを登録してください</a>
      {% else %}
        <a href="" target="_blank" class="mypage-info-footer">{{ commander_info }}</a>
      {% endif %}


  </div><!-- mypage-main-info -->
</div><!-- mypage-main-box -->
<!-- --------------------↓↓↓↓チームごとの募集状況、応募状況、気になるイベント、フォロー中↓↓↓↓--------------------- -->
{% if commander_info == 0 %}
  <h2 style="text-align: center;">ログインまたはチームを登録してください</h2>
{% else %}
  <div class="tabbox">
    <div class="mypage-center-box">
      <div class="tabs">
        <div id="menu">
          <ul>
          {% for my_team in my_teams %}
            <li><button><a href="#{{ my_team.tab_name }}" class="{{ my_team.tab_name }} button" onclick="ChangeTab('{{ my_team.tab_name }}'); return false;">{{ my_team.organization_name }}{{ my_team.club_name }}  </a></button></li>
          {% endfor %}
          </ul>
        </div>
      </div>
      <br>
    </div>
    <div class="mypage-sub-box">
    {% for my_team in my_teams %}

      <div id="{{ my_team.tab_name }}" class="tab"><br>
          <h1>{{ my_team.organization_name }}{{ my_team.club_name }}({{ my_team.school_attribute }})</h1>

          <h3 class="team-action-title">募集状況</h3>
          <table class="table">
            <tbody>
              {% for post_event in my_team.post_events %}
              <tr>
                <th><a href="{% url 'tramino:match_detail' post_event.id %}" style="text-decoration: none;">{{ post_event.event_name }}</a><a href="{% url 'tramino:edit_event' post_event.id %}" style="color: black;">更新する</a>　<a href="{% url 'tramino:delete_event' post_event.id %}" style="color: black;">削除する</a></th>
              </tr>
              {% endfor %}
            </tbody>
          </table>

          <h3 class="team-action-title">応募したイベント</h3>
          <table class="table">
            <tbody>
              {% for apply_event in my_team.apply_events %}
              <tr>
                <th><a href="{% url 'tramino:match_detail' apply_event.event_post_id.id %}" style="text-decoration: none;">{{ apply_event.event_post_id.event_name }}</a></th>
              </tr>
              {% endfor %}
            </tbody>
          </table>

          <h3 class="team-action-title">気になるイベント</h3>
          <table class="table">
            <tbody>
            {% for favorite_event in my_team.favorite_events %}
              <tr>
                <th><a href="{% url 'tramino:match_detail' favorite_event.event_post_id.id %}" style="text-decoration: none;">{{ favorite_event.event_post_id.event_name }}</a></th>
              </tr>
              {% endfor %}
            </tbody>
          </table>


          <h3 class="team-action-title">フォロー中のチーム</h3>
          <table class="table">
            <tbody>
            {% for favorite_team in my_team.favorite_teams %}
              <tr>
                <th><a href="{% url 'tramino:team_detail' favorite_team.host_team_id.id %}" style="text-decoration: none;">{{ favorite_team.host_team_id.organization_name }}{{ favorite_team.host_team_id.club_name }}({{ favorite_team.host_team_id.school_attribute }})</a></th>
              </tr>
              {% endfor %}
            </tbody>
          </table>
      </div>
    {% endfor %}
    </div><!-- mypage-sub-info -->
  </div><!--tab-box-->
{% endif %}


{% endblock %}


{% block js %}


<!--テーブル切り替え-->
<script type="text/javascript">

var lists = {{ tab_names | safe }};

  function ChangeTab(tabname) {
     // タブメニュー実装
  for (  var i = 0;  i < lists.length;  i++  ) {

  document.getElementById(( lists[ i ] )).style.display = 'none';

  }
     // タブメニュー実装
     document.getElementById(tabname).style.display = 'block';

  }


</script>

<script type="text/javascript">
$(function(){
  var btn = $('button');
  btn.click(function(){
    btn.removeClass('active');
    $(this).addClass('active');
    // console.log('done');

  });
});
</script>


<!-- ページを開いた際の最初に表示されるタブの選択 -->
<script type="text/javascript">
  ChangeTab('tab1');
</script>


{% endblock %}

templates/tramino/myteams.html
{% extends 'tramino/base.html' %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">あなたが登録したチームのリスト</li>
{% endblock %}

{% block content %}
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>団体名</th>
        <th>部活名</th>
        <th>分類</th>
        <th>プロフィール完成率</th>
        <th>詳細</th>
        <th>更新</th>
        <th>削除</th>
      </tr>
    </thead>
    <tbody>
      {% for teaminformations in my_teams %}
        <tr>
          <td>{{ teaminformations.organization_name }}</td>
          <td>{{ teaminformations.club_name }}</td>
          <td>{{ teaminformations.school_attribute }}</td>
          <td>{{ teaminformations.score }}%</td>
          <td><a href="{% url 'tramino:myteams_detail' teaminformations.id %}">詳細画面へ</a></td>
          <td><a href="{% url 'tramino:edit_myteams' teaminformations.id %}">更新画面へ</a></td>
          <td><a href="{% url 'tramino:delete_myteams' teaminformations.id %}">削除画面へ</a></td>
          
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <br>
  <a href="{% url 'tramino:create' %}" class="mypage-btn">登録チームの追加</a>
{% endblock %}